cuda: True
data:
        train_data: 'train_env_task_set_20_full_reduced_tasks_single'
        test_data: 'test_env_task_set_10_full_reduced_tasks_single'
log:
        print_every: 20
        print_long_every: 50
train:
        epochs: 500
        batch_size: 32
        num_workers: 10
        lr: 0.0001
        overfit: False
        agents: '3'
        loss_close: 1.0
        loss_goal: 1.0
test:
        num_iters: 20
model:
        max_nodes: 150
        max_class_objects: 37
        max_actions: 10
        num_states: 4
        num_attributes: 6
        hidden_size: 200
        max_tsteps: 50
        goal_inp: True
        gated: False

