data:
        train_data: 'dataset_graph_pred_overfit_train.pkl'
        test_data: 'dataset_graph_pred_overfit_train.pkl'
log:
        print_every: 20
        print_long_every: 50
train:
        epochs: 200
        batch_size: 8
        num_workers: 10
        lr: 0.001
        overfit: False
        agents: '0'

test:
        num_iters: 20
model:
        max_nodes: 150
        max_class_objects: 37
        max_actions: 10
        num_states: 4
        num_attributes: 6
        hidden_size: 200
        max_tsteps: 100
        relative_coords: False
        goal_inp: True

